### ISSUE TITLE
Why did you use Bloom instead Bloomz

### ISSUE THREAD

**Issue by linhduongtuan** [AGI-Edgerunners/LLM-Adapters#1]
Hello everyone,
I would like to inquire as to why you have chosen Bloom-7b1 as your paper description. As far as I know, BigScience recommends using Bloomz variants, which can be found by following this link: https://huggingface.co/bigscience/bloomz.

I am concerned that your evaluation results shown in Table 1 may be biased. Would it be possible for you to use Bloomz-7b1 instead and re-evaluate? Thank you in advance.
Best regards,
Linh

**Comment by demoleiwang** [comment]
@linhduongtuan 
Thank you for your suggestion! We will explore Bloomz and make updates to the arXiv paper promptly.
