### ISSUE TITLE
Couldn't get the same accuracy as the table (7B model LoRA)

### ISSUE THREAD

**Issue by ywen666** [AGI-Edgerunners/LLM-Adapters#26]
Hi thanks for open-sourcing this amazing repo! I tried to replicate the table in the `README` by running the LoRA fine-tuning in `math_running_commands` and evaluate the fine-tuned model by `multi_dataset_eval.py`. I only achieved single digit accuracy on most datasets (~3% on gsm8k). I tried to evaluate the provided the checkpoint (13B LoRA) which indeed gave me the same result as the table.
I wonder if there is anything I was missing to reproduce the table for the 7B size model.

**Comment by ywen666** [comment]
It turns out I was using the official `peft` library which is different than the `peft` provided in this repo. After switching to the provided `peft`, I can get the same accuracy as the table. 
Closing the issue.

**Comment by ChaoGaoUCR** [comment]
Hello, Do You mind sharing one copy of your setting with me?
I am having trouble reproducing the results as well...

**Comment by ywen666** [comment]
I just followed the inference and eval in the README. I couldn't get the same result because I have official peft installed so when my script launched, it was using the official `peft` library instead of the one provided here.

**Comment by ChaoGaoUCR** [comment]
Got it,
Did you change anything in the evaluation.py?
Seems the JSON parsing is different... 
Also, I couldn't find the peft+llama official tuning result and datasets,
You mind sharing the link with me if possible?

Thanks
Chao
