### ISSUE TITLE
Peft version problem

### ISSUE THREAD

**Issue by marlin-codes** [AGI-Edgerunners/LLM-Adapters#39]
"The version of PEFT you are using is not compatible, please use a version that is greater than 0.5.0"

**Comment by HZQ950419** [comment]
Hi,

Please uninstall peft and re-run.

**Comment by marlin-codes** [comment]
> Hi,
> 
> Please uninstall peft and re-run.

Thanks for your quick reply. The problem persists when I re-install it.
My operation is to uninstall peft
'pip uninstall peft'
Then, I installed peft with 
`cd peft/
pip install -e .`

But it still has the same problem.

**Comment by HZQ950419** [comment]
Hi, 

You can try to uninstall peft and re-run without installation coz in `finetune.py` Line 16 we indicated the location of the package. If still have the same error, please check if you have installed the huggingface PEFT in the public environment.

**Comment by marlin-codes** [comment]
The problem has been solved by uninstalling peft. Thanks for your assistance.
