### ISSUE TITLE
How to Reproduce BLOOMz-7b and GPT-j-6 results?

### ISSUE THREAD

**Issue by Ocean-627** [AGI-Edgerunners/LLM-Adapters#50]
Dear Authors,
    Excellent work! I just wonder how I can reproduce BLOOMz-7b and GPT-j-6 results. It seems that the training command mentioned in the previous issue only applies to llama.
    Thank you very much.

**Comment by HZQ950419** [comment]
Hi,

We have updated the `math_running_commands` file. You can find the command to reproduce BLOOMz-7b and GPT-j-6B results.
