### ISSUE TITLE
Gibberish output 

### ISSUE THREAD

**Issue by Aradhye2002** [AGI-Edgerunners/LLM-Adapters#63]
Hi,

I tried finetuning the 7B model on math10k dataset and then running evaluate.py. However, I get the following response for the question:

Instruction: Tell me about alpacas.
Response: 1ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ<s> ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ<s> ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ<s> ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ<s> ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ<s> ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ<s> ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ<s> ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ<s>ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

Can you tell me what's going wrong?

**Comment by Zhenyu001225** [comment]
The same questions...

**Comment by Zhenyu001225** [comment]
The same question...

**Comment by Zhenyu001225** [comment]
> Hi,
> 
> I tried finetuning the 7B model on math10k dataset and then running evaluate.py. However, I get the following response for the question:
> 
> Instruction: Tell me about alpacas. Response: 1ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
> 
> Can you tell me what's going wrong?

Hi, you can try pip install transformers==0.35.0
I think it's the version problem.

**Comment by Aradhye2002** [comment]
Thanks a lot it worked. I downgraded to a different version though since 0.35.0 was not available.

**Comment by Zhenyu001225** [comment]
> Thanks a lot it worked. I downgraded to a different version though since 0.35.0 was not available.

You're welcome~ Yes I remembered the wrong version. Anyway, downgraded to another version will work for this problem~

**Comment by Zhenyu001225** [comment]
> Hi,
> 
> I tried finetuning the 7B model on math10k dataset and then running evaluate.py. However, I get the following response for the question:
> 
> Instruction: Tell me about alpacas. Response: 1ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
> 
> Can you tell me what's going wrong?

Hi, can you reproduce the results in the table? I don't know what happened with my implementation..

**Comment by Aradhye2002** [comment]
Hi @Zhenyu001225 sorry missed your comment. I am able to reproduce to some extent with Lora, however I can't seem to figure out which modules they have applied Lora to...
